# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Nis_New_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setMinimumSize(QtCore.QSize(813, 353))
        Dialog.setMaximumSize(QtCore.QSize(813, 353))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Nigeria_Immigration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 791, 331))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(500, 50, 281, 261))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/Nigeria_Immigration.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(14, 42, 437, 82))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 75 36pt \"MS Shell Dlg 2\";\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.refreshButton = QtWidgets.QToolButton(self.frame)
        self.refreshButton.setGeometry(QtCore.QRect(15, 140, 59, 19))
        self.refreshButton.setArrowType(QtCore.Qt.NoArrow)
        self.refreshButton.setObjectName("refreshButton")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(14, 130, 437, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(14, 167, 435, 146))
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.inputLabel = QtWidgets.QLabel(self.frame_2)
        self.inputLabel.setGeometry(QtCore.QRect(12, 43, 411, 16))
        self.inputLabel.setMouseTracking(False)
        self.inputLabel.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.inputLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inputLabel.setText("")
        self.inputLabel.setObjectName("inputLabel")
        self.outputLabel = QtWidgets.QLabel(self.frame_2)
        self.outputLabel.setGeometry(QtCore.QRect(12, 99, 411, 16))
        self.outputLabel.setText("")
        self.outputLabel.setObjectName("outputLabel")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(12, 62, 411, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setGeometry(QtCore.QRect(12, 118, 411, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.repostButton = QtWidgets.QToolButton(self.frame_2)
        self.repostButton.setGeometry(QtCore.QRect(14, 71, 47, 19))
        self.repostButton.setObjectName("repostButton")
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.progressBar.setGeometry(QtCore.QRect(120, 70, 311, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.loadDataButton = QtWidgets.QPushButton(self.frame_2)
        self.loadDataButton.setGeometry(QtCore.QRect(13, 13, 75, 23))
        self.loadDataButton.setToolTipDuration(-1)
        self.loadDataButton.setFlat(False)
        self.loadDataButton.setObjectName("loadDataButton")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(94, 13, 201, 16))
        self.label_4.setObjectName("label_4")
        self.repostButton.raise_()
        self.inputLabel.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.outputLabel.raise_()
        self.progressBar.raise_()
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 791, 31))
        self.frame_3.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.inputLabel.setBuddy(Dialog.input directry)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Nigeria Immigration Service"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; color:#005500;\">NIGERIA IMMIGRATION SERVICE </span></p><p align=\"center\"><span style=\" font-size:22pt; color:#005500;\">POSTING APPLICATION</span></p></body></html>"))
        self.refreshButton.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">click to refresh the App.</span></p></body></html>"))
        self.refreshButton.setText(_translate("Dialog", "Refresh.."))
        self.repostButton.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">click to repost workers</span></p></body></html>"))
        self.repostButton.setText(_translate("Dialog", "Repost"))
        self.loadDataButton.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Click to load the data of the workers due for reposting</span></p></body></html>"))
        self.loadDataButton.setStatusTip(_translate("Dialog", "Load image Button"))
        self.loadDataButton.setText(_translate("Dialog", "Load "))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-style:italic; color:#ff0000;\">click to load the csv record of the workers</span></p></body></html>"))
import icons_rc
